import math

# Game settings
RES = WIDHT, HEIGHT = 1400, 800
HALF_WIDHT = WIDHT // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 0

PLAYER_POS = 1.5, 5 # mini map
PLAYER_ANGEL = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002
PLAYER_SIZE_SCALE = 60 

# Raycasting settings
FOV = math.pi / 3
HALF_FOV = FOV/2
NUM_RAYS = WIDHT // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDHT / math.tan(HALF_FOV)
SCALE = WIDHT // NUM_RAYS

# Texture Settings
TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2