import math

# Game settings
RES = WIDHT, HEIGHT = 1600, 900
FPS = 60

PLAYER_POS = 1.5, 5 # mini map
PLAYER_ANGEL = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002

# Raycasting settings
FOV = math.py / 3
HALF_FOV = FOV/2
NUM_RAYS = WIDHT // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20